### ISSUE TITLE
Cannot sign in 

### ISSUE THREAD

**Issue by salmansheri** [ethanmick/time-tracker#2]
![error](https://github.com/ethanmick/time-tracker/assets/95226945/870485bb-de50-4017-bab7-1515aa631dc4)

Cannot login

**Comment by ethanmick** [comment]
Thanks! I'll take a look. My hunch is it's a database thingy with Postgres going to sleep. If you try it twice in a row (the first time it'll error) does the second time work? Let me know, thanks!

**Comment by ethanmick** [comment]
I've migrated to a new database. I'm hoping this resolves errors on the first load, which I think is what you experienced. Please let me know if you cannot log in.
